INTENT_LABELS = [
    "billing",
    "technical_support",
    "account_management",
    "order_status",
    "general_inquiry",
    "feedback",
]

# Small hand-labeled training set. Not exhaustive, but enough signal for
# bert-base-uncased to learn a real decision boundary between the five
# intents (vs. the notebook's original random, untrained classifier head).
TRAIN_EXAMPLES = [
    # billing
    ("Why was I charged twice this month?", "billing"),
    ("I need a copy of my last invoice.", "billing"),
    ("Can you explain this extra fee on my bill?", "billing"),
    ("How do I update my credit card on file?", "billing"),
    ("I want a refund for last week's purchase.", "billing"),
    ("My payment failed, can you check what happened?", "billing"),
    ("Is there a discount if I pay annually?", "billing"),
    ("I was billed after I cancelled my subscription.", "billing"),
    ("Can I get an itemized receipt for tax purposes?", "billing"),
    ("How can I check my billing status?", "billing"),
    ("The amount charged doesn't match the price I saw.", "billing"),
    ("I'd like to switch from monthly to yearly billing.", "billing"),
    # technical_support
    ("The app keeps crashing when I open the dashboard.", "technical_support"),
    ("I can't log in, it says invalid credentials.", "technical_support"),
    ("The website is throwing a 500 error on checkout.", "technical_support"),
    ("Your app is stuck on the loading screen.", "technical_support"),
    ("None of the buttons on the settings page work.", "technical_support"),
    ("I'm getting an error code E1042, what does it mean?", "technical_support"),
    ("Two-factor authentication isn't sending me a code.", "technical_support"),
    ("The mobile app won't sync with my desktop account.", "technical_support"),
    ("How can I reset my password?", "technical_support"),
    ("I forgot my password and the reset link isn't arriving.", "technical_support"),
    ("The page is completely blank after I log in.", "technical_support"),
    ("Uploads keep failing halfway through.", "technical_support"),
    # account_management
    ("I'd like to change the email address on my account.", "account_management"),
    ("How do I delete my account permanently?", "account_management"),
    ("Can I merge two accounts into one?", "account_management"),
    ("I want to downgrade my plan to the free tier.", "account_management"),
    ("How do I add a team member to my workspace?", "account_management"),
    ("Please update my shipping address for future orders.", "account_management"),
    ("I need to change my username.", "account_management"),
    ("How do I upgrade to the premium plan?", "account_management"),
    ("Can you remove my phone number from the account?", "account_management"),
    ("I want to transfer ownership of this account to a colleague.", "account_management"),
    ("How do I turn off email notifications?", "account_management"),
    ("Please cancel my subscription, I don't want to be charged again.", "account_management"),
    ("Close my account so I stop getting billed.", "account_management"),
    ("I want to cancel before the next billing cycle.", "account_management"),
    ("Deactivate my account, I no longer need the service.", "account_management"),
    # order_status
    ("Where is my order? It's been a week.", "order_status"),
    ("Can you give me a tracking number for my package?", "order_status"),
    ("My order says delivered but I never received it.", "order_status"),
    ("How long until my order ships?", "order_status"),
    ("I need to change the delivery address for an order I just placed.", "order_status"),
    ("The tracking page hasn't updated in three days.", "order_status"),
    ("Can I cancel an order that hasn't shipped yet?", "order_status"),
    ("My package arrived damaged.", "order_status"),
    ("I received the wrong item in my order.", "order_status"),
    ("When will my order arrive?", "order_status"),
    ("The shirt I got is the wrong size, I ordered a large.", "order_status"),
    ("This isn't what I ordered, I got a different product.", "order_status"),
    ("You sent me the wrong color, I asked for black not white.", "order_status"),
    ("The item that showed up doesn't match what I purchased.", "order_status"),
    # general_inquiry
    ("What are your customer support hours?", "general_inquiry"),
    ("Hi, I have a quick question.", "general_inquiry"),
    ("Do you have a physical store I can visit?", "general_inquiry"),
    ("What's the best way to contact a human agent?", "general_inquiry"),
    ("Do you ship internationally?", "general_inquiry"),
    ("Is there a mobile app for iOS?", "general_inquiry"),
    ("Can you tell me more about your company?", "general_inquiry"),
    ("What languages does support cover?", "general_inquiry"),
    ("Hello, is anyone available to chat?", "general_inquiry"),
    # feedback
    ("Thanks for your help earlier!", "feedback"),
    ("Just wanted to say your support team was amazing today.", "feedback"),
    ("This app is honestly the best I've used, great job.", "feedback"),
    ("I'm really unhappy with the service I received.", "feedback"),
    ("The new update is fantastic, well done to the team!", "feedback"),
    ("Your customer service was terrible and unhelpful.", "feedback"),
    ("I love how easy this product is to use.", "feedback"),
    ("The support agent I spoke to was incredibly rude.", "feedback"),
    ("Great job on the redesign, it looks awesome!", "feedback"),
    ("I want to complain about how long it took to get a response.", "feedback"),
    ("Just leaving some feedback — the checkout flow felt clunky.", "feedback"),
    ("You guys always go above and beyond, really appreciate it.", "feedback"),
]

# Unseen, differently-phrased queries used only for evaluation — a stand-in
# for "real world" traffic the model wasn't trained on.
REAL_WORLD_TEST_CASES = [
    ("I got double charged on my card this week, can someone look into it?", "billing"),
    ("There's a weird $9.99 charge I don't recognize.", "billing"),
    ("The site crashes every time I try to check out.", "technical_support"),
    ("I can't get back into my account, password reset email never came.", "technical_support"),
    ("I'd like to update the email tied to my profile.", "account_management"),
    ("Please close my account, I don't want to be billed again.", "account_management"),
    ("It's been 10 days and my package still says 'in transit'.", "order_status"),
    ("I ordered a blue jacket but got a red one instead.", "order_status"),
    ("What time does your support team come online?", "general_inquiry"),
    ("Just wanted to say thanks, you guys are great!", "feedback"),
    ("Really appreciate how quickly that got sorted out today.", "feedback"),
    ("Honestly the worst experience I've had with a support team.", "feedback"),
]
